@TraderForge.API_HostAddress = http://localhost:5116

GET {{TraderForge.API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST http://localhost:5116/api/identity/register
Content-Type: application/json

{
  "email": "test15@traderforge.com",
  "password": "SuperSecretPassword123!"
}

###

POST http://localhost:5116/api/identity/login
Content-Type: application/json

{
  "email": "test15@traderforge.com",
  "password": "SuperSecretPassword123!"
}

###

GET http://localhost:5116/api/identity/vip-lounge
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlM2YxYWUzYi1jNDQ4LTQ4NWEtOGZkNC1mYzhlMzEwNmRjNjEiLCJlbWFpbCI6InRlc3QxNUB0cmFkZXJmb3JnZS5jb20iLCJyb2xlIjoiVHJhZGVyIiwibmJmIjoxNzc3OTIzODg2LCJleHAiOjE3Nzc5MzEwODYsImlhdCI6MTc3NzkyMzg4NiwiaXNzIjoiVHJhZGVyRm9yZ2VBUEkiLCJhdWQiOiJUcmFkZXJGb3JnZVJlYWN0QXBwIn0.-iemotaJg5z0VAtVvuWlEIJ072NKNM7sdx-naocIu8E



###
 