@TraderForge.API_HostAddress = http://localhost:5116

GET {{TraderForge.API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST http://localhost:5116/api/identity/register
Content-Type: application/json

{
  "email": "test15@traderforge.com",
  "password": "SuperSecretPassword123!"
}

###

POST http://localhost:5116/api/identity/login
Content-Type: application/json

{
  "email": "test15@traderforge.com",
  "password": "SuperSecretPassword123!"
}

###

GET http://localhost:5116/api/identity/vip-lounge
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMjYwZjE1MS0xOTdiLTRjNTUtYmJlYy1hOTcwY2YwYmI4YzMiLCJlbWFpbCI6InRlc3QxNUB0cmFkZXJmb3JnZS5jb20iLCJyb2xlIjoiVHJhZGVyIiwibmJmIjoxNzc2ODk2MzQ3LCJleHAiOjE3NzY5MDM1NDcsImlhdCI6MTc3Njg5NjM0NywiaXNzIjoiVHJhZGVyRm9yZ2VBUEkiLCJhdWQiOiJUcmFkZXJGb3JnZVJlYWN0QXBwIn0.oKDoGQnAtIvpydz4ZyMF76D5tI1p9QmpiSalBvEIUfk


###
