@hostAddress = http://localhost:5116
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOGU3NTNhZS0xYmJkLTRmMGQtOTUzMC04NzkzOTE0MmFmNWIiLCJlbWFpbCI6InRlc3QxNkB0cmFkZXJmb3JnZS5jb20iLCJyb2xlIjoiVHJhZGVyIiwibmJmIjoxNzc4MzU0NzE5LCJleHAiOjE3NzgzNjE5MTksImlhdCI6MTc3ODM1NDcxOSwiaXNzIjoiVHJhZGVyRm9yZ2VBUEkiLCJhdWQiOiJUcmFkZXJGb3JnZVJlYWN0QXBwIn0.O8TjJJYyuU05mOLXDo9TqZCeGu93JtDhrCPUmoUBaas


GET {{hostAddress}}/weatherforecast/
Accept: application/json

###

POST {{hostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "test16@traderforge.com",
  "password": "SuperSecretPassword123!"
}

###

POST {{hostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "test16@traderforge.com",
  "password": "SuperSecretPassword123!"
}

###

GET {{hostAddress}}/api/identity/vip-lounge
Authorization: bearer {{token}}

###

GET {{hostAddress}}/api/subscription/plans

###

GET {{hostAddress}}/api/subscription/trader-plan
Authorization: bearer {{token}}

###

POST {{hostAddress}}/api/subscription/change-plan
Content-Type: application/json
Authorization: bearer {{token}}

{
  "newPlanId": "22222222-2222-2222-2222-222222222222"
}
 